; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "³¡¾°±à¼­Æ÷"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "dada_gou"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\SceneEditor.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "root.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\SceneEditor.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "³¡¾°±à¼­Æ÷°²×°°ü.exe"
InstallDir "$PROGRAMFILES\³¡¾°±à¼­Æ÷"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "Base\config.ini"
  SetOutPath "$INSTDIR\iconengines"
  File "Base\iconengines\qsvgicon.dll"
  SetOutPath "$INSTDIR"
  File "Base\icudt51.dll"
  File "Base\icuin51.dll"
  File "Base\icuuc51.dll"
  SetOutPath "$INSTDIR\imageformats"
  File "Base\imageformats\qgif.dll"
  File "Base\imageformats\qico.dll"
  File "Base\imageformats\qjpeg.dll"
  File "Base\imageformats\qmng.dll"
  File "Base\imageformats\qsvg.dll"
  File "Base\imageformats\qtga.dll"
  File "Base\imageformats\qtiff.dll"
  File "Base\imageformats\qwbmp.dll"
  SetOutPath "$INSTDIR\platforms"
  File "Base\platforms\qminimal.dll"
  File "Base\platforms\qoffscreen.dll"
  File "Base\platforms\qwindows.dll"
  SetOutPath "$INSTDIR"
  File "Base\Qt5Core.dll"
  File "Base\Qt5Gui.dll"
  File "Base\Qt5Widgets.dll"
  File "Base\SceneEditor.exe"
  CreateDirectory "$SMPROGRAMS\³¡¾°±à¼­Æ÷"
  CreateShortCut "$SMPROGRAMS\³¡¾°±à¼­Æ÷\³¡¾°±à¼­Æ÷.lnk" "$INSTDIR\SceneEditor.exe"
  CreateShortCut "$DESKTOP\³¡¾°±à¼­Æ÷.lnk" "$INSTDIR\SceneEditor.exe"
  SetOutPath "$INSTDIR"
  File "Base\vcredist_sp1_x86.exe"
  ExecWait '"$INSTDIR\vcredist_sp1_x86.exe"'
SectionEnd

Section -AdditionalIcons
  CreateShortCut "$SMPROGRAMS\³¡¾°±à¼­Æ÷\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\SceneEditor.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\SceneEditor.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) ÒÑ³É¹¦µØ´ÓÄãµÄ¼ÆËã»úÒÆ³ý¡£"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "ÄãÈ·ÊµÒªÍêÈ«ÒÆ³ý $(^Name) £¬Æä¼°ËùÓÐµÄ×é¼þ£¿" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\vcredist_sp1_x86.exe"
  Delete "$INSTDIR\TestData\NewMap.json"
  Delete "$INSTDIR\TestData\cat.png"
  Delete "$INSTDIR\TestData\0.png"
  Delete "$INSTDIR\SceneEditor.exe"
  Delete "$INSTDIR\Qt5Widgets.dll"
  Delete "$INSTDIR\Qt5Gui.dll"
  Delete "$INSTDIR\Qt5Core.dll"
  Delete "$INSTDIR\platforms\qwindows.dll"
  Delete "$INSTDIR\platforms\qoffscreen.dll"
  Delete "$INSTDIR\platforms\qminimal.dll"
  Delete "$INSTDIR\imageformats\qwbmp.dll"
  Delete "$INSTDIR\imageformats\qtiff.dll"
  Delete "$INSTDIR\imageformats\qtga.dll"
  Delete "$INSTDIR\imageformats\qsvg.dll"
  Delete "$INSTDIR\imageformats\qmng.dll"
  Delete "$INSTDIR\imageformats\qjpeg.dll"
  Delete "$INSTDIR\imageformats\qico.dll"
  Delete "$INSTDIR\imageformats\qgif.dll"
  Delete "$INSTDIR\icuuc51.dll"
  Delete "$INSTDIR\icuin51.dll"
  Delete "$INSTDIR\icudt51.dll"
  Delete "$INSTDIR\iconengines\qsvgicon.dll"
  Delete "$INSTDIR\config.ini"

  Delete "$SMPROGRAMS\³¡¾°±à¼­Æ÷\Uninstall.lnk"
  Delete "$DESKTOP\³¡¾°±à¼­Æ÷.lnk"
  Delete "$SMPROGRAMS\³¡¾°±à¼­Æ÷\³¡¾°±à¼­Æ÷.lnk"

  RMDir "$SMPROGRAMS\³¡¾°±à¼­Æ÷"
  RMDir "$INSTDIR\TestData"
  RMDir "$INSTDIR\platforms"
  RMDir "$INSTDIR\imageformats"
  RMDir "$INSTDIR\iconengines"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd